server:
  port: 8090

spring:
  application:
    name: currency-and-account-service

  #Datasource
  # datasource:
  #   url: jdbc:mysql://localhost:3306/moneyaccountdatabase
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   username: root
  #   password: Satgaino1@

#Jpa
  jpa:
    hibernate:
      ddl-auto: update

#Kafka
  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
#Cloud

#Circuit Breaker
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 5000
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
        allowHealthIndicatorToFail: false
#Jeager
tracing:
  url: http://localhost:4318/v1/traces

#Actuator
management:
  tracing:
    sampling:
      probability: 1.0

#Variables
# jwkSetUri: http://localhost:8088/oauth2/jwks
# jwtAuthoritiesClaimName: roles
# issuer: http://localhost:8088

#Eureka
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:9000/eureka/
